version: '3.8'

services:
  face-verification:
    build: .
    ports:
      - "5000:5000"
    environment:
      - WORKERS_PER_CORE=1
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    restart: unless-stopped